sudo: required

install:
  - wget https://github.com/concourse/concourse/releases/download/v5.4.0/fly-5.4.0-linux-amd64.tgz
  - tar -xvzf fly-5.4.0-linux-amd64.tgz
  - export PATH="./fly:$PATH"

script:
  - ./validate-pipelines.sh

branches:
  only:
    - master
