sudo: required

install:
  - wget https://github.com/concourse/concourse/releases/download/v5.4.0/fly-5.4.0-linux-amd64.tgz
  - tar -xvzf fly-5.4.0-linux-amd64.tgz

script:
  - for i in pipelines/*.yml; do ./fly validate-pipeline -c $i; done

branches:
  only:
    - master
