platform: linux

image_resource:
  type: docker-image
  source:
    repository: google/cloud-sdk
    tag: slim

params:
  SERVICE_ACCOUNT_JSON:
  KUBERNETES_NAMESPACE:
  KUBERNETES_CLUSTER:
  GCP_PROJECT_NAME:
  KUBERNETES_FILE_PATH:
  KUBERNETES_SELECTOR:
  SLEEP_TIME_FOR_STARTUP:

inputs:
  - name: kubernetes-file

run:
  path: sh
  args:
    - -exc
    - |
      apt install kubectl

      cat >~/gcloud-service-key.json <<EOL
      $SERVICE_ACCOUNT_JSON
      EOL

      # Use gcloud service account to configure kubectl
      gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
      gcloud container clusters get-credentials ${KUBERNETES_CLUSTER} --zone europe-west2 --project ${GCP_PROJECT_NAME}

      # Apply the kube file
      kubectl apply -f ${KUBERNETES_FILE_PATH} --namespace=${KUBERNETES_NAMESPACE}

      # Get deployment status
      kubectl get deployments -o wide --namespace=${KUBERNETES_NAMESPACE} -l ${KUBERNETES_SELECTOR}

      # Sleep to give time for services to start
      sleep ${SLEEP_TIME_FOR_STARTUP}

      # Get deployment status
      kubectl get deployments -o wide --namespace=${KUBERNETES_NAMESPACE} -l ${KUBERNETES_SELECTOR}
