platform: linux

image_resource:
  type: docker-image
  source:
    repository: eu.gcr.io/census-gcr/gcloud-kubectl

params:
  GCP_PROJECT_NAME:
  KUBERNETES_CLUSTER:
  KUBERNETES_DEPLOYMENT_NAME:
  KUBERNETES_FILE_PATH:
  KUBERNETES_FILE_PREFIX:
  SERVICE_ACCOUNT_JSON:
  WAIT_UNTIL_AVAILABLE_TIMEOUT:

inputs:
  - name: kubernetes-repo
run:
  path: sh
  args:
    - -exc
    - |
      cat >~/gcloud-service-key.json <<EOL
      $SERVICE_ACCOUNT_JSON
      EOL

      # Use gcloud service account to configure kubectl
      gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
      gcloud container clusters get-credentials ${KUBERNETES_CLUSTER} --zone europe-west2 --project ${GCP_PROJECT_NAME}

      # Apply persistent volume config
      kubectl apply -f ${KUBERNETES_FILE_PATH}/${KUBERNETES_FILE_PREFIX}-persistentvolume.yml --record

      # Apply cronjob config
      kubectl apply -f ${KUBERNETES_FILE_PATH}/${KUBERNETES_FILE_PREFIX}-cronjob.yml --record

      # Get cronjob status
      kubectl get cronjobs --field-selector metadata.name=${KUBERNETES_DEPLOYMENT_NAME} -o wide
