platform: linux

image_resource:
  type: docker-image
  source:
    repository: eu.gcr.io/census-ci/gcloud-kubectl

params:
  SERVICE_ACCOUNT_JSON:
  KUBERNETES_NAMESPACE:
  KUBERNETES_CLUSTER:
  GCP_PROJECT_NAME:
  KUBERNETES_DEPLOYMENT_NAME:
  KUBERNETES_SELECTOR:
  KUBERNETES_FILE_PATH:
  KUBERNETES_FILE_PREFIX:
  WAIT_UNTIL_AVAILABLE_TIMEOUT:

inputs:
  - name: kubernetes-repo
run:
  path: sh
  args:
    - -exc
    - |
      cat >~/gcloud-service-key.json <<EOL
      $SERVICE_ACCOUNT_JSON
      EOL

      # Use gcloud service account to configure kubectl
      gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
      gcloud container clusters get-credentials ${KUBERNETES_CLUSTER} --zone europe-west2 --project ${GCP_PROJECT_NAME}

      # Apply service config
      kubectl apply -f ${KUBERNETES_FILE_PATH}/${KUBERNETES_FILE_PREFIX}-service.yml --namespace=${KUBERNETES_NAMESPACE} --record

      # Apply deployment config
      kubectl apply -f ${KUBERNETES_FILE_PATH}/${KUBERNETES_FILE_PREFIX}-deployment.yml --namespace=${KUBERNETES_NAMESPACE} --record

      # Wait for rollout to finish
      kubectl rollout status deploy ${KUBERNETES_DEPLOYMENT_NAME} --watch=true --timeout=${WAIT_UNTIL_AVAILABLE_TIMEOUT} --namespace=${KUBERNETES_NAMESPACE}

      # Get deployment status
      kubectl get deployments "-l ${KUBERNETES_SELECTOR}" -o wide --namespace=${KUBERNETES_NAMESPACE}
