
platform: linux
image_resource:
  type: docker-image
  source: 
    repository: alpine
inputs: 
  - name: release
outputs: 
  - name: unpacked-release
run:
  path: sh
  args: 
    - -exc
    - tar -xvf release/*.tar.gz -C unpacked-release --strip-components=1
