platform: linux
image_resource:
  type: docker-image
  source:
    repository: eu.gcr.io/census-gcr-rm/rm/census-rm-toolbox
    username: _json_key
    password: ((gcp.service_account_json))
params:
  GCP_PROJECT_NAME:
  SERVICE_ACCOUNT_JSON:
  KUBERNETES_CLUSTER:
inputs:
  - name: census-rm-whitelist
run:
  path: bash
  args:
    - -exc
    - |
      export GOOGLE_APPLICATION_CREDENTIALS=/home/toolbox/gcloud-service-key.json
      export GCP_PROJECT=$GCP_PROJECT_NAME
      cat >$GOOGLE_APPLICATION_CREDENTIALS <<EOL
      $SERVICE_ACCOUNT_JSON
      EOL
      gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
      gcloud container clusters get-credentials ${KUBERNETES_CLUSTER} --zone europe-west2 --project ${GCP_PROJECT}

      ls -al /
      ls -al

      export WORKING_DIRECTORY=`pwd`
      echo Working directory is $WORKING_DIRECTORY
      
      cd /home/toolbox/cloudshell_utilities
      ./whitelist.sh $GCP_PROJECT $WORKING_DIRECTORY/census-rm-whitelist/environments/$GCP_PROJECT