resource_types:

  - name: concourse-pipeline
    type: docker-image
    source:
      repository: concourse/concourse-pipeline-resource

resources:

  - name: census-rm-deploy
    type: git
    source:
      uri: git@github.com:ONSdigital/census-rm-deploy.git
      paths:
      - "pipelines"
      private_key: ((github.service_account_private_key))

  - name: pipelines
    type: concourse-pipeline
    source:
      target: http://concourse-web:8080/
      teams:
      - name: rm
        username: rm
        password: ((concourse.team-pass))

jobs:

  - name: fly-pipelines
    plan:
    - get: census-rm-deploy
      trigger: true
    - put: pipelines
      params:
        pipelines:

        - name: fly-pipelines
          team: rm
          config_file: census-rm-deploy/pipelines/concourse-pipelines.yml
          unpaused: true

        - name: CI-Whitelodge Deploy
          team: rm
          config_file: census-rm-deploy/pipelines/ci-sit-kubernetes-pipeline.yml
          unpaused: true
          vars:
            ci-gcp-environment-name: ci
            ci-gcp-project-name: census-rm-ci
            ci-kubernetes-cluster-name: rm-k8s-cluster
            terraform-branch: master
            acceptance-tests-image: eu.gcr.io/census-gcr-rm/rm/census-rm-acceptance-tests:latest
            sit-gcp-environment-name: whitelodge
            sit-gcp-project-name: census-rm-whitelodge
            sit-kubernetes-cluster-name: rm-k8s-cluster

        - name: census-rm-blacklodge
          team: rm
          config_file: census-rm-deploy/pipelines/manual-release-pipeline.yml
          vars:
            gcp-environment-name: blacklodge
            gcp-project-name: census-rm-blacklodge
            kubernetes-cluster-name: rm-k8s-cluster
            acceptance-tests-image: eu.gcr.io/census-gcr-rm/rm/census-rm-acceptance-tests:v1.0.0
            kubernetes-release: v1.0.0

        - name: build-images
          team: rm
          config_file: census-rm-deploy/pipelines/docker-build-pipeline.yml
          unpaused: true
          vars:
            docker-registry-ci: eu.gcr.io/census-rm-ci
            docker-registry-gcr: eu.gcr.io/census-gcr-rm

        - name: release-images
          team: rm
          config_file: census-rm-deploy/pipelines/docker-release-pipeline.yml
          unpaused: true
          vars:
            docker-registry-ci: eu.gcr.io/census-rm-ci
            docker-registry-gcr: eu.gcr.io/census-gcr-rm
