resource_types:

  # Recent release 3.0.0 needs the fly version to be 6.1.0 to work. Ours is currently 5.6.0 so we need to pin the resource 
  # to a previous release instead of using the latest image.
  - name: concourse-pipeline
    type: docker-image
    source:
      repository: concourse/concourse-pipeline-resource
      tag: 2.2.0

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:

  - name: slack-alert
    type: slack-notification
    source:
      url: ((slack.webhook))

  - name: census-rm-deploy
    type: git
    source:
      uri: git@github.com:ONSdigital/census-rm-deploy.git
      paths:
      - "pipelines"
      - "tasks"
      private_key: ((github.service_account_private_key))

  - name: pipelines
    type: concourse-pipeline
    source:
      target: http://concourse-web:8080/
      teams:
      - name: rm
        username: rm
        password: ((concourse.team-pass))

jobs:

  - name: fly-pipelines
    plan:
    - get: census-rm-deploy
    - put: pipelines
      on_failure:
        put: slack-alert
        params:
          icon_emoji: ":concourse:"
          username: Concourse
          attachments: [
            {
              "fallback": "$BUILD_JOB_NAME failed. See build: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME",
              "title": "$BUILD_JOB_NAME failed",
              "title_link": "$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME",
              "fields": [
                {
                  "title": "Pipeline",
                  "value": "$BUILD_PIPELINE_NAME",
                  "short": true
                },
                {
                  "title": "Build",
                  "value": "#$BUILD_NAME",
                  "short": true
                }
              ],
              "color": "#ff0000"
            }
          ]

      on_error:
        put: slack-alert
        params:
          icon_emoji: ":concourse:"
          username: Concourse
          attachments: [
            {
              "fallback": "$BUILD_JOB_NAME errored. See build: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME",
              "title": "$BUILD_JOB_NAME errored",
              "title_link": "$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME",
              "fields": [
                {
                  "title": "Pipeline",
                  "value": "$BUILD_PIPELINE_NAME",
                  "short": true
                },
                {
                  "title": "Build",
                  "value": "#$BUILD_NAME",
                  "short": true
                }
              ],
              "color": "#f58a3d"
            }
          ]

      params:
        pipelines:

        - name: fly-pipelines
          team: rm
          config_file: census-rm-deploy/pipelines/concourse-pipelines.yml
          unpaused: true

        - name: census-rm-greylodge
          team: rm
          config_file: census-rm-deploy/pipelines/manual-release-pipeline.yml
          vars:
            gcp-environment-name: greylodge
            gcp-project-name: census-rm-greylodge
            kubernetes-cluster-name: rm-k8s-cluster
            prometheus-config: release/monitoring/prometheus-values.yml
            grafana-config: release/monitoring/grafana-deployment.yml
            rabbitmq-file: census-rm-deploy/tasks/rabbitmq-provision.yml
            rabbitmq-production-setup: true

        - name: census-rm-preprod
          team: rm
          config_file: census-rm-deploy/pipelines/prod-manual-release-pipeline.yml
          vars:
            gcp-environment-name: preprod
            gcp-project-name: census-rm-preprod
            kubernetes-cluster-name: rm-k8s-cluster
            rabbit-config: release/rabbitmq/values_prod.yml
            prometheus-config: release/monitoring/prometheus-values.yml
            grafana-config: release/monitoring/grafana-deployment.yml
            rabbitmq-file: census-rm-deploy/tasks/rabbitmq-provision.yml
            rabbitmq-production-setup: true

        - name: census-rm-prod
          team: rm
          config_file: census-rm-deploy/pipelines/prod-manual-release-pipeline.yml
          vars:
            gcp-environment-name: prod
            gcp-project-name: census-rm-prod
            kubernetes-cluster-name: rm-k8s-cluster
            rabbit-config: release/rabbitmq/values_prod.yml
            prometheus-config: release/monitoring/prometheus-values.yml
            grafana-config: release/monitoring/grafana-deployment.yml
            rabbitmq-file: census-rm-deploy/tasks/rabbitmq-provision.yml
            rabbitmq-production-setup: true
