---
resources:
- name: census-rm-deploy
  type: git
  source:
    uri: git@github.com:ONSdigital/census-rm-deploy.git
    private_key: ((github.service_account_private_key))

- name: census-rm-kubernetes-repo
  type: git
  source:
    uri: git@github.com:ONSdigital/census-rm-kubernetes.git
    private_key: ((github.service_account_private_key))

- name: census-rm-terraform
  type: git
  source:
    branch: ((terraform-branch))
    uri: git@github.com:ONSdigital/census-rm-terraform.git
    private_key: ((github.service_account_private_key))

- name: batch-runner-repo
  type: git
  source:
    uri: git@github.com:ONSdigital/census-rm-qid-batch-runner.git
    private_key: ((github.service_account_private_key))

- name: census-rm-kubernetes-microservices-repo
  type: git
  source:
    uri: git@github.com:ONSdigital/census-rm-kubernetes.git
    private_key: ((github.service_account_private_key))
    paths: [microservices/*]

- name: census-rm-kubernetes-ops-repo
  type: git
  source:
    uri: git@github.com:ONSdigital/census-rm-kubernetes.git
    private_key: ((github.service_account_private_key))
    paths: [optional/ops-*]

- name: acceptance-tests-repo
  type: git
  source:
    uri: git@github.com:ONSdigital/census-rm-acceptance-tests.git
    private_key: ((github.service_account_private_key))
    paths: [kubernetes.env, tasks/*]

- name: acceptance-tests-docker-image
  type: docker-image
  source:
    repository: eu.gcr.io/census-rm-ci/rm/census-rm-acceptance-tests
    username: _json_key
    password: ((gcp.service_account_json))

- name: action-scheduler-docker-latest
  type: docker-image
  source:
    repository: eu.gcr.io/census-rm-ci/rm/census-rm-action-scheduler
    username: _json_key
    password: ((gcp.service_account_json))

- name: case-api-docker-latest
  type: docker-image
  source:
    repository: eu.gcr.io/census-rm-ci/rm/census-rm-case-api
    username: _json_key
    password: ((gcp.service_account_json))

- name: case-processor-docker-latest
  type: docker-image
  source:
    repository: eu.gcr.io/census-rm-ci/rm/census-rm-case-processor
    username: _json_key
    password: ((gcp.service_account_json))

- name: uac-qid-service-docker-latest
  type: docker-image
  source:
    repository: eu.gcr.io/census-rm-ci/rm/census-rm-uac-qid-service
    username: _json_key
    password: ((gcp.service_account_json))

- name: pubsubsvc-docker-latest
  type: docker-image
  source:
    repository: eu.gcr.io/census-rm-ci/rm/census-rm-pubsub
    username: _json_key
    password: ((gcp.service_account_json))

- name: ops-docker-latest
  type: docker-image
  source:
    repository: eu.gcr.io/census-rm-ci/rm/census-rm-ops
    username: _json_key
    password: ((gcp.service_account_json))

- name: qid-batch-runner-docker-latest
  type: docker-image
  source:
    repository: eu.gcr.io/census-rm-ci/rm/census-rm-qid-batch-runner
    username: _json_key
    password: ((gcp.service_account_json))

- name: print-file-service-docker-latest
  type: docker-image
  source:
    repository: eu.gcr.io/census-rm-ci/rm/census-rm-print-file-service
    username: _json_key
    password: ((gcp.service_account_json))


jobs:


- name: deploy-infrastructure
  serial: true
  serial_groups: [action-scheduler, case-api, case-processor, uac-qid-service, ops, pubsubsvc, print-file-service]
  max_in_flight: 1
  plan:
  - get: census-rm-terraform
    trigger: true
  - get: census-rm-kubernetes-repo
  - task: "Build & Deploy Infrastructure"
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: google/cloud-sdk
      params:
        AUTO_APPLY: true
        DEV_DUMMY_PGP: true
        DEV_LOCAL_SFTP: true
        DEV_PUBSUB: true
        DEV_SCALE_DOWN: true
        DISABLE_CI_BINDING: true
        ENV: ((gcp-environment-name))
        GOOGLE_APPLICATION_CREDENTIALS: /root/gcloud-service-key.json
        KEEP_TMP_K8S: true
        ADMIN_SERVICE_ACCOUNT_JSON: ((gcp-admin-account-json))
      inputs:
        - name: census-rm-terraform
        - name: census-rm-kubernetes-repo
      run:
        path: bash
        args:
          - -exc
          - |
            apt-get install -y unzip procps
            git clone https://github.com/kamatama41/tfenv.git ~/.tfenv && \
            ln -s /root/.tfenv/bin/* /usr/local/bin
            cat >$GOOGLE_APPLICATION_CREDENTIALS <<EOL
            $ADMIN_SERVICE_ACCOUNT_JSON
            EOL
            gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
            cp -R census-rm-kubernetes-repo/ census-rm-terraform/tmp_rm_kube
            cd census-rm-terraform
            tfenv install
            curl -L https://git.io/get_helm.sh | bash && \
            helm init --client-only && \
            helm plugin install https://github.com/rimusz/helm-tiller
            ./apply.sh


# Kubernetes Config
- name: action-scheduler
  serial: true
  serial_groups: [action-scheduler]
  plan:
  - get: census-rm-terraform
    trigger: true
    passed: [deploy-infrastructure]
  - get: census-rm-kubernetes-microservices-repo
    trigger: true
  - get: action-scheduler-docker-latest
    trigger: true
    params:
      skip_download: true
  - get: census-rm-deploy
  - task: apply-service-and-deploy
    file: census-rm-deploy/tasks/kubectl-apply-service-and-deploy.yml
    params:
      SERVICE_ACCOUNT_JSON: ((gcp.service_account_json))
      GCP_PROJECT_NAME: ((gcp-project-name))
      KUBERNETES_CLUSTER: ((kubernetes-cluster-name))
      KUBERNETES_DEPLOYMENT_NAME: action-scheduler
      KUBERNETES_SELECTOR: app=action-scheduler
      KUBERNETES_FILE_PATH: kubernetes-repo/microservices
      KUBERNETES_FILE_PREFIX: action-scheduler
      WAIT_UNTIL_AVAILABLE_TIMEOUT: 200s
    input_mapping: {kubernetes-repo: census-rm-kubernetes-microservices-repo}

- name: case-api
  serial: true
  serial_groups: [case-api]
  plan:
  - get: census-rm-terraform
    trigger: true
    passed: [deploy-infrastructure]
  - get: census-rm-kubernetes-microservices-repo
    trigger: true
  - get: case-api-docker-latest
    trigger: true
    params:
      skip_download: true
  - get: census-rm-deploy
  - task: apply-deployment
    file: census-rm-deploy/tasks/kubectl-apply-service-and-deploy.yml
    params:
      SERVICE_ACCOUNT_JSON: ((gcp.service_account_json))
      GCP_PROJECT_NAME: ((gcp-project-name))
      KUBERNETES_CLUSTER: ((kubernetes-cluster-name))
      KUBERNETES_DEPLOYMENT_NAME: case-api
      KUBERNETES_SELECTOR: app=case-api
      KUBERNETES_FILE_PATH: kubernetes-repo/microservices
      KUBERNETES_FILE_PREFIX: case-api
      WAIT_UNTIL_AVAILABLE_TIMEOUT: 200s
    input_mapping: {kubernetes-repo: census-rm-kubernetes-microservices-repo}

- name: case-processor
  serial: true
  serial_groups: [case-processor]
  plan:
  - get: census-rm-terraform
    trigger: true
    passed: [deploy-infrastructure]
  - get: census-rm-kubernetes-microservices-repo
    trigger: true
  - get: case-processor-docker-latest
    trigger: true
    params:
      skip_download: true
  - get: census-rm-deploy
  - task: apply-deployment
    file: census-rm-deploy/tasks/kubectl-apply-deployment.yml
    params:
      SERVICE_ACCOUNT_JSON: ((gcp.service_account_json))
      GCP_PROJECT_NAME: ((gcp-project-name))
      KUBERNETES_CLUSTER: ((kubernetes-cluster-name))
      KUBERNETES_DEPLOYMENT_NAME: case-processor
      KUBERNETES_SELECTOR: app=case-processor
      KUBERNETES_FILE_PATH: kubernetes-repo/microservices
      KUBERNETES_FILE_PREFIX: case-processor
      WAIT_UNTIL_AVAILABLE_TIMEOUT: 200s
    input_mapping: {kubernetes-repo: census-rm-kubernetes-microservices-repo}

- name: uac-qid-service
  serial: true
  serial_groups: [uac-qid-service]
  plan:
  - get: census-rm-terraform
    trigger: true
    passed: [deploy-infrastructure]
  - get: census-rm-kubernetes-microservices-repo
    trigger: true
  - get: uac-qid-service-docker-latest
    trigger: true
    params:
      skip_download: true
  - get: census-rm-deploy
  - task: apply-service-and-deploy
    file: census-rm-deploy/tasks/kubectl-apply-service-and-deploy.yml
    params:
      SERVICE_ACCOUNT_JSON: ((gcp.service_account_json))
      GCP_PROJECT_NAME: ((gcp-project-name))
      KUBERNETES_CLUSTER: ((kubernetes-cluster-name))
      KUBERNETES_DEPLOYMENT_NAME: uacqidservice
      KUBERNETES_SELECTOR: app=uacqidservice
      KUBERNETES_FILE_PATH: kubernetes-repo/microservices
      KUBERNETES_FILE_PREFIX: uac-qid-service
      WAIT_UNTIL_AVAILABLE_TIMEOUT: 200s
    input_mapping: {kubernetes-repo: census-rm-kubernetes-microservices-repo}

- name: pubsubsvc
  serial: true
  serial_groups: [pubsubsvc]
  plan:
  - get: census-rm-terraform
    trigger: true
    passed: [deploy-infrastructure]
  - get: census-rm-kubernetes-microservices-repo
    trigger: true
  - get: pubsubsvc-docker-latest
    trigger: true
    params:
      skip_download: true
  - get: census-rm-deploy
  - task: apply-deployment
    file: census-rm-deploy/tasks/kubectl-apply-deployment.yml
    params:
      SERVICE_ACCOUNT_JSON: ((gcp.service_account_json))
      GCP_PROJECT_NAME: ((gcp-project-name))
      KUBERNETES_CLUSTER: ((kubernetes-cluster-name))
      KUBERNETES_DEPLOYMENT_NAME: pubsubsvc
      KUBERNETES_SELECTOR: app=pubsubsvc
      KUBERNETES_FILE_PATH: kubernetes-repo/microservices
      KUBERNETES_FILE_PREFIX: pubsub
      WAIT_UNTIL_AVAILABLE_TIMEOUT: 200s
    input_mapping: {kubernetes-repo: census-rm-kubernetes-microservices-repo}

- name: print-file-service
  serial: true
  serial_groups: [print-file-service]
  plan:
  - get: census-rm-terraform
    trigger: true
    passed: [deploy-infrastructure]
  - get: census-rm-kubernetes-microservices-repo
    trigger: true
  - get: print-file-service-docker-latest
    trigger: true
    params:
      skip_download: true
  - get: census-rm-deploy
  - task: apply-deployment
    file: census-rm-deploy/tasks/kubectl-apply-deployment.yml
    params:
      SERVICE_ACCOUNT_JSON: ((gcp.service_account_json))
      GCP_PROJECT_NAME: ((ci-gcp-project-name))
      KUBERNETES_CLUSTER: ((kubernetes-cluster-name))
      KUBERNETES_DEPLOYMENT_NAME: printfilesvc
      KUBERNETES_SELECTOR: app=printfilesvc
      KUBERNETES_FILE_PATH: kubernetes-repo/microservices
      KUBERNETES_FILE_PREFIX: print-file-service
      WAIT_UNTIL_AVAILABLE_TIMEOUT: 200s
    input_mapping: {kubernetes-repo: census-rm-kubernetes-microservices-repo}

- name: ops
  serial: true
  serial_groups: [ops]
  plan:
  - get: census-rm-terraform
    trigger: true
    passed: [deploy-infrastructure]
  - get: census-rm-kubernetes-ops-repo
    trigger: true
  - get: ops-docker-latest
    trigger: true
    params:
      skip_download: true
  - get: census-rm-deploy
  - task: apply-deployment
    file: census-rm-deploy/tasks/kubectl-apply-service-and-deploy.yml
    params:
      SERVICE_ACCOUNT_JSON: ((gcp.service_account_json))
      GCP_PROJECT_NAME: ((gcp-project-name))
      KUBERNETES_CLUSTER: ((kubernetes-cluster-name))
      KUBERNETES_DEPLOYMENT_NAME: ops
      KUBERNETES_SELECTOR: app=ops
      KUBERNETES_FILE_PATH: kubernetes-repo/optional
      KUBERNETES_FILE_PREFIX: ops
      WAIT_UNTIL_AVAILABLE_TIMEOUT: 200s
    input_mapping: {kubernetes-repo: census-rm-kubernetes-ops-repo}

- name: "Acceptance Tests"
  serial: true
  serial_groups: [action-scheduler, case-api, case-processor, uac-qid-service, pubsubsvc, print-file-service]
  plan:
  - get: census-rm-terraform
    trigger: true
    passed: [action-scheduler, case-api, case-processor, uac-qid-service, pubsubsvc, print-file-service]
  - get: acceptance-tests-repo
  - get: batch-runner-repo
  - get: acceptance-tests-docker-image
    trigger: true
    params:
      skip_download: true
  - get: census-rm-kubernetes-microservices-repo
    trigger: true
    passed: [action-scheduler, case-api, case-processor, uac-qid-service, pubsubsvc, print-file-service]
  - get: action-scheduler-docker-latest
    trigger: true
    passed: [action-scheduler]
    params:
      skip_download: true
  - get: case-api-docker-latest
    trigger: true
    passed: [case-api]
    params:
      skip_download: true
  - get: case-processor-docker-latest
    trigger: true
    passed: [case-processor]
    params:
      skip_download: true
  - get: uac-qid-service-docker-latest
    trigger: true
    passed: [uac-qid-service]
    params:
      skip_download: true
  - get: pubsubsvc-docker-latest
    trigger: true
    passed: [pubsubsvc]
    params:
      skip_download: true
  - get: qid-batch-runner-docker-latest
    trigger: true
    params:
      skip_download: true
  - get: print-file-service-docker-latest
    trigger: true
    params:
      skip_download: true
  - task: "Run Acceptance Tests (in K8s)"
    file: acceptance-tests-repo/tasks/kubectl-run-acceptance-tests.yml
    params:
      SERVICE_ACCOUNT_JSON: ((gcp.service_account_json))
      GCP_PROJECT_NAME: ((gcp-project-name))
      KUBERNETES_CLUSTER: ((kubernetes-cluster-name))
      ACCEPTANCE_TESTS_IMAGE: ((acceptance-tests-image))
    input_mapping: {acceptance-tests-repo: acceptance-tests-repo}
